---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hao.zhou.
--- DateTime: 2025/3/7 16:22
---
-- 令牌管理核心逻辑
-- version: 1.2.1
-- fix: 修复旧令牌清理逻辑


--[[
Redis 令牌管理增强脚本
功能：在保证原子性的前提下实现：
1. 自动清理过期令牌
2. 客户端维度令牌数量控制
3. 多设备会话管理
4. 高性能批量操作
参数：
KEYS[1]: 客户端用户令牌集合键 (CLIENT_USER_TOKENS_KEY)
KEYS[2]: 用户令牌集合键 (USER_TOKEN_MAPPING_KEY)
KEYS[3]: 授权记录键前缀 (OAUTH2_AUTHORIZATION_KEY_PREFIX)
KEYS[4]: 设备令牌映射键 (DEVICE_TOKEN_MAPPING_KEY)
ARGV[1]: 新访问令牌值
ARGV[2]: 设备 ID（为空时不记录设备）
ARGV[3]: 过期时间（秒）
ARGV[4]: 序列化的授权对象 JSON
ARGV[5]: 当前时间戳（秒）
ARGV[6]: 最大允许令牌数
ARGV[7]: authorizationId]]

--[[ 辅助函数：安全数字转换 ]]--
local function toNum(str)
    if type(str) == "string" then
        local num = tonumber(str)
        if not num then
            error("invalid number: " .. str)
        end
        return num
    end
    return str -- 处理可能透传的数字类型
end

--[[ 主逻辑 ]]--
local function main()
    -- 转换所有数字参数
    local currentTime = toNum(ARGV[5])
    local maxTokens = toNum(ARGV[6])
    local expiresIn = toNum(ARGV[3])
    local authorizationId = ARGV[7] -- 新增参数

    --[[ 阶段 1：过期令牌清理 ]]--
    -- ZREMRANGEBYSCORE 删除所有 score <= currentTime 的过期令牌
    redis.call('ZREMRANGEBYSCORE', KEYS[1], 0, currentTime)

    --[[ 阶段 2：令牌数量控制 ]]--
    local tokenCount = redis.call('ZCARD', KEYS[1])
    if tokenCount >= maxTokens then
        -- 计算需要移除的令牌数量
        local removeCount = tokenCount - maxTokens + 1

        -- 获取待移除的旧令牌（按 score 升序，即最早到期的）
        local oldTokens = redis.call('ZRANGE', KEYS[1], 0, removeCount - 1)

        --[[ 批量删除关联数据 ]]--
        -- 批量删除旧令牌关联数据
        for _, token in ipairs(oldTokens) do
            local tokenToIdKey = 'oauth2:authorization:token_to_id:'..token
            local oldAuthorizationId = redis.call('GET', tokenToIdKey)
            redis.call('DEL', tokenToIdKey)   -- 删除 Token→ID 映射

            if oldAuthorizationId then
                redis.call('DEL', 'oauth2:authorization:id:'..oldAuthorizationId) -- 删除 ID→Token 映射
            end
        end

        if #oldTokens > 0 then
            -- 构造完整的授权记录键列表
            local delKeys = {}
            for i, token in ipairs(oldTokens) do
                delKeys[i] = KEYS[3] .. token -- 拼接完整键路径
            end

            -- 批量删除授权记录（减少网络往返）
            redis.call('DEL', unpack(delKeys))

            -- 从用户令牌集合移除
            redis.call('SREM', KEYS[2], unpack(oldTokens))
        end


        -- 从有序集合移除旧令牌
        redis.call('ZREMRANGEBYRANK', KEYS[1], 0, removeCount - 1)
    end

    --[[ 阶段 3：存储新令牌 ]]--
    local newScore = currentTime + expiresIn  -- 过期时间戳作为 score

    -- 添加到有序集合并设置 TTL
    redis.call('ZADD', KEYS[1], newScore, ARGV[1])
    redis.call('EXPIRE', KEYS[1], expiresIn)  -- 对齐令牌有效期

    -- 存储完整的授权记录（独立键）
    redis.call('SET', KEYS[3] .. ARGV[1], ARGV[4], 'EX', expiresIn)

    -- 存储 ID → Token 映射
    redis.call('SET', 'oauth2:authorization:id:'..authorizationId, ARGV[1], 'EX', expiresIn)

    -- 存储 Token → ID 映射
    redis.call('SET', 'oauth2:authorization:token_to_id:'..ARGV[1], authorizationId, 'EX', expiresIn)

    -- 维护用户令牌集合
    redis.call('SADD', KEYS[2], ARGV[1])

    --[[ 阶段 4：设备信息记录 ]]--
    if ARGV[2] ~= '' then
        -- 设备 ID -> 令牌映射（相同设备登录时覆盖旧令牌）
        redis.call('HSET', KEYS[4], ARGV[2], ARGV[1])
    end

    return 1 -- 返回成功状态
end

-- 执行主函数
return main()